name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo 'heroku-cli installed'

      - name: Heroku Authentication
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Authenticating with Heroku..."
          heroku auth:token --api-key=$HEROKU_API_KEY

      - name: Configure Git for Heroku
        run: |
          echo "Setting up Git for Heroku..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          heroku git:remote -a projet7-perron-app
          git remote -v

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Deploying to Heroku..."
          git push heroku main
